### ISSUE TITLE
Plugin to resize RectExtents interactively in the viewport

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-turn-based-rpg#108]
Create a tool script to modify the size of RectExtents interactively on the canvas. 
It's not that it's necessary but I'm looking to learn more about in-viewport interactions for tutorials, and to start to make use of Godot's powerful plugin api and tool modes

**Comment by henriiquecampos** [comment]
I think this could be a Plugin itself, instead of a simple `tool` script as with an `EditorPlugin` you can have access to some Editor related classes that I think would be necessary, such as:

- [EditorInterface](https://docs.godotengine.org/en/3.0/classes/class_editorinterface.html#editorinterface)
- [EditorSelection](https://docs.godotengine.org/en/3.0/classes/class_editorselection.html#editorselection)

And some other stuff that can be useful:

- [Add Controls to Containers](https://docs.godotengine.org/en/3.0/classes/class_editorplugin.html#class-editorplugin-add-control-to-container)
- [Foward Canvas GUI Input](https://docs.godotengine.org/en/3.0/classes/class_editorplugin.html#class-editorplugin-forward-canvas-gui-input) (for shortcuts?)

Also to get some events to control the display of the handlers with:

- [EditorSelection.selection_changed](https://docs.godotengine.org/en/3.0/classes/class_editorselection.html#editorselection) **signal** to get when a RectExtents is actually selected and show/hide the handlers properly

I couldn't find a way on how to actually display the handlers like Godot does with `Shape2Ds`, `Line2Ds`, `Polygon2Ds` etc... while searching in the Godot Editor repository, but I imagine you can use some sort of `Button` or `TextureButton` and instance them, just like in a game.

**Comment by NathanLovato** [comment]
Actually I got it well started already. You can draw textures or shapes in the viewport directly. I'll try to finish and push it a little later

**Comment by NathanLovato** [comment]
![godot-3 1-alpha-2_2018-12-08_13-17-11](https://user-images.githubusercontent.com/12694995/49682658-51bee380-fafb-11e8-8305-dbe247994375.png)

Got the drawing started, just got to fix the input and make setting the rect extents work now

**Comment by NathanLovato** [comment]
@Zireael07 it needs more work but the plugin is up. Tutorials will follow :)

**Comment by NathanLovato** [comment]
Left to do: fix the plugin stealing input from other tools. It should only consume input when the user clicks and drags on one of the anchors
