### ISSUE TITLE
InteractivePawn should trigger actions when the player presses a key or touches it

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-turn-based-rpg#115]
They shouldn't have a "facing" dictionary either with up to 4 active directions at a time. To interact with an NPC, the player should have to:

- tap on it in touch mode
- press an action key on the keyboard or the controller

And automatic trigger upon walking in an area around the pawn should work differently: it should have some trigger area or something.

**Comment by GraphicEdit** [comment]
Can  I get Godot 3.1 ?

**Comment by guilhermehto** [comment]
What do you mean, @GraphicEdit ?

**Comment by guilhermehto** [comment]
Yes, this project is developed using Godot 3.1, which currently is in Alpha stage

**Comment by guilhermehto** [comment]
The goal for the issue is to add another function that will allow the player to start an interaction when he wants to?  This way, the pawns can either auto start the interaction or wait for player input?

Regarding the "facing", it's just another option that was added in case we want the NPC's to only trigger interactions from a given direction. The distance for the interaction can also be increased if needed. There's already support for Area2D triggers that don't rely on ray casts. Want to remove them anyway?

**Comment by GraphicEdit** [comment]
How Can I get it  (Godot 3.1),?

**Comment by NathanLovato** [comment]
> This way, the pawns can either auto start the interaction or wait for player input?

Yes, and now it should support touch (tapping on the cell where an NPC is)

@GraphicEdit https://godotengine.org/article/dev-snapshot-godot-3-1-alpha-2
You can find the link quickly on any search engine. This is not the place to get support, please use Discord or something next time.

**Comment by GraphicEdit** [comment]
ok.. Thanks..
