### ISSUE TITLE
[Proposal] Implement Database from Json files using Data Driven Programing

### ISSUE THREAD

**Issue by MarianoGnu** [GDquest/godot-turn-based-rpg#86]
About a month ago i did [this script](https://gist.github.com/MarianoGnu/3c3bd5e58bb2cea85354bda97de1cf2a) for a personal project, i think this can match any case where you make a data driven approach, using this approach, creating a new item, skill, or even maybe enemy could be as easy as adding it's data structure to a Json file.
How it works: there's a const value in the script currently pointing to res://game_data/ folder, this could be changed. but inside this folder you place subfolders with the names of different categories (in my case these was: items, perks, fighter_classes, etc) and inside every folder you place whatever quantity of json files with any name you like, these files have only 2 requeriments:
1. the file must be an array, even if it only has 1 or 0 objects
2. every object inside the array must have an id property, if this id is repeated for every category, the last one readen will override the previous one.
[This is an example](https://gist.github.com/MarianoGnu/29dbc5a79fdfb3dacadd8f247cf6259d) of how an Item structure looks for my game

After the files are loaded, the Node having this script attacked to will have all this information on a Dictionary called `data`. this variable has a property member with the name of every folder on the main directory, and from there you can access every object on the json file with the id provided on the json file, so for example to access to the "Photon Gun2" weapon you should use the path `data.items[2]`

The `filter_data` method: the script also has a `filter_data(source, criteria)` tool that will gather from the objects on the database those who matches a certain criteria. for example this line of code:
`filter_data(data.items, {type="BARRIER"})`
will return all the items that can be equiped on the BARRIER slot.

**Comment by NathanLovato** [comment]
Which problem does this solve in this project?

We already use Godot's Resources system to store data, which is built just for that, used throughout the engine, is well-tested, and optimized.

I'll need some really good arguments to maintain our own system and to lose the ability to edit data in the inspector.

**Comment by willnationsdev** [comment]
I definitely agree that Resources are a far better approach for Godot projects (especially demos like this one).

**Comment by MarianoGnu** [comment]
Mainly, that json files are faster to read and edit, you dont have to lookup for nodes and/or resources on the file system or opening an scecific scene to find and change what you want to change.

**Comment by NathanLovato** [comment]
> that for example how champions and heroes on league of legends are done

They probably have some tools that serialize the data. I'd be really surprised if the designers balanced the characters from JSON instead of using some UI while the game is running.

> json files are faster to read and edit

Maybe for a developer like you who's used to working with JSON. I don't think so in general: a folder with a flat structure of text files, which is exactly what items are in the game, is just as easy to edit.

And contrary to JSON Godot recognizes the format and lets you edit files from the inspector *as well*, from nested inspectors...

As you say yourself:

> I agree this is not the most user friendly

So it's not workflow-friendly either.

This is an open source project, that we're building so the Godot community can use it and developers of all horizons can join and contribute. We should avoid adding dependencies on external tools and making design tasks less accessible to designers.

As I said above, you need strong arguments for us to ditch a well-tested, built-in, optimized system in favor of doing our own from scratch. For now, I'm not convinced at all. I only see drawbacks.

**Comment by salvob41** [comment]
I understand that this is an educational projects for Godot but when developing for a game that want to be released, usually (often) you need support from backend, especially if you want some online feature ( multiplayer? buy items? score ladder? ). For this you will connect to external services, and JSON is a pretty viable way (the best if online). 

Plus, (but this is my opinion) Resources are not user-friendly and/or workflow-friendly at all, at least as they are right now: It might be hard backtracking resources attached to `.tscn` file. 

Example for this project regarding `battle_template` Resource:  
- `Party member` has a `Resource export var` (that can be ANY Resource for Godot editor). 
-   Resources like `Godette.tres` and `Robi.tres` have a PackedScene in it. In order to find out which PackedScene they have you cannot click the scene on the editor of resource but you have to click the arrow next to the editor and click `Show in FileSystem`. 
- Accessing to the `<nameCharacter>Anim.tscn` will show the scene of a Position2D with Sprites and AnimationPlayers (Where will be added in the main actor scene? With the information we have from this process, we cannot know). 
- `Battler.tscn` has another resource called `template` and it is a Resource as well. What kind of resource?  .... 
... is this workflow-friendly ? 

A JSON has key->value data. it might be verbose but tells you exactly what you need and it is understandable by other services that you (most likely) will end up using

**Comment by NathanLovato** [comment]
It's late here, I'll answer in greater details later, but don't forget that:

1. You can edit and browse resources directly from the file system
2. You can edit a resource attached to an existing one as a sub-resource
3. Godot updates paths and dependencies for you, this is a big thing for refactoring

There's one question that's still left without an answer: which problem does it solve in this project?

NB I do understand that json is an efficient format, I use and used it myself. I'd pick a good old table instead for e.g. items, and anything that doesn't need a nested structure, like items.

Having worked as a game designer, with a variety of tools and plain data... Which is faster depends a lot on the context. Again, resources are also editable as text files, so if you use a flat structure it's about the same as working with a list of json objects.

**Comment by MarianoGnu** [comment]
yeah, all these features you mentioned are new in 3.1
The issues i mentioned where working with 2.x and 3.0

**Comment by NathanLovato** [comment]
And this is a Godot 3.1 project

**Comment by MarianoGnu** [comment]
All right, we could reopen this discusion if we ever find a problem with the workflow and need to figure out another easier way of doing things.
