### ISSUE TITLE
Simplify the Battler node

### ISSUE THREAD

**Issue by salvob41** [GDquest/godot-turn-based-rpg#98]
I would like to put an alert how complicated handling the battler has becomimg with the awesome growth of the project. 

So, before it is too late I will resume its current shenanigans:
```
class_name BattlerTemplate

export var anim : PackedScene
export var stats : Resource
export var skills : Array

```
- `Battler.tscn` wants a Resource: `export var template : Resource` line 6. It is not specified which resource is but it is `BattlerTemplate` (line 28)
- this resource will be added bisected and assigned to `skills`(line 29) and the `anim` is added as a child to the `skin` node. 
`Anim` is a PackedScene with Position2D as root and two Sprites and AnimationPlayer.
`Skin` is a Position2D and has an AnimationPlayer and basically is the same of the `CharacterAnim` above. 
- In `CombatScene.gd`  in line (51:58) and (65:73) the template from `PartyMember` is added to the `BattlerNode`.
PartyMember has a source script inside the scene (so not really easy to spot) and basically it wants the same Resource above mentioned but called in different way. 

What do you guys think? Can we make this process a little bit smoother? It won't be easy for new contributors ...

**Comment by godofgrunts** [comment]
It's definitely not easy. Took me forever to map it out the first time, but I have no idea how to make it easier.

**Comment by nhydock** [comment]
I've been meaning to revisit this, as I admit the approach I took is a bit aggressive at forcing everything into generic, yet consistent, battle representations.  The main point was to separate the actual battler representation from what it actually meant to be a combat capable entity.  However, godot's resource interface, while already powerful, is definitely lacking due to the inability to actually type exported resources on scripts.  I'll look into cleaning this up tonight.

**Comment by NathanLovato** [comment]
Sure, we can figure out a way to simplify that. No need to make it sound like it's our last chance or something, you can refactor that anytime.

There's reasons behind all of these decisions as Nicholas explains. Regarding the anim, it's just that the character's animation and the base battler class are separate files, so that:

1. an artist can work on animation while somebody else works on the battler
2. we can compose a battler instead of using inheritance, which is one of Godot's biggest strengths

Anyway every time I get back into some script people contributed, I take the time to refactor and simplify it, if possible. Let's just keep doing that as we go.

**Comment by NathanLovato** [comment]
Done with f69506185201dc185616f9653936a88c99b588d3, closing for now as that's a nice step towards making the battlers more visual and the code a little more accessible, but also because we'll keep refactoring as we go.

You can always open new issues about specific actionable problems and/or solutions you come up with.
